apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: 'true'
  name: hnc-admin-role
  namespace: hnc-system
rules:
- apiGroups:
  - hnc.x-k8s.io
  resources:
  - '*'
  verbs:
  - '*'
