apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: allow-tailscale
  namespace: cilium
spec:
  endpointSelector: {}
  ingress:
  - fromCIDRSet:
    - cidr: fd7a:115c:a1e0::/48
