apiVersion: v1
data:
  config.yaml: |2

    analytics:
      reporting_enabled: false
    auth_enabled: false
    chunk_store_config:
      chunk_cache_config:
        background:
          writeback_buffer: 500000
          writeback_goroutines: 1
          writeback_size_limit: 500MB
        default_validity: 0s
        memcached:
          batch_size: 4
          parallelism: 5
        memcached_client:
          addresses: dnssrvnoa+_memcached-client._tcp.loki-chunks-cache.loki.svc
          consistent_hash: true
          max_idle_conns: 72
          timeout: 2000ms
    common:
      compactor_address: 'http://loki-backend:3100'
      path_prefix: /var/loki
      replication_factor: 3
      ring:
        instance_enable_ipv6: true
        kvstore:
          store: memberlist
      storage:
        s3:
          access_key_id: ${AWS_ACCESS_KEY_ID}
          bucketnames: hfym-loki-chunks
          endpoint: ${BUCKET_ENDPOINT}
          insecure: false
          s3forcepathstyle: false
          secret_access_key: ${AWS_SECRET_ACCESS_KEY}
    compactor:
      compactor_ring:
        instance_enable_ipv6: true
        kvstore:
          store: memberlist
    distributor:
      ring:
        instance_enable_ipv6: true
        kvstore:
          store: memberlist
    frontend:
      scheduler_address: ""
      tail_proxy_url: http://loki-querier.loki.svc.cluster.local:3100
    frontend_worker:
      scheduler_address: ""
    index_gateway:
      mode: simple
      ring:
        instance_enable_ipv6: true
        kvstore:
          store: memberlist
    ingester:
      chunk_encoding: snappy
      lifecycler:
        enable_inet6: true
        ring:
          kvstore:
            store: memberlist
    limits_config:
      ingestion_burst_size_mb: 50
      ingestion_rate_mb: 20
      max_cache_freshness_per_query: 10m
      query_timeout: 300s
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      split_queries_by_interval: 15m
      volume_enabled: true
    memberlist:
      bind_addr:
      - '::'
      join_members:
      - loki-memberlist
    pattern_ingester:
      enabled: false
    querier:
      max_concurrent: 4
    query_range:
      align_queries_with_step: true
      cache_results: true
      results_cache:
        cache:
          background:
            writeback_buffer: 500000
            writeback_goroutines: 1
            writeback_size_limit: 500MB
          default_validity: 12h
          memcached_client:
            addresses: dnssrvnoa+_memcached-client._tcp.loki-results-cache.loki.svc
            consistent_hash: true
            timeout: 500ms
            update_interval: 1m
    query_scheduler:
      scheduler_ring:
        instance_enable_ipv6: true
        kvstore:
          store: memberlist
    ruler:
      ring:
        kvstore:
          store: memberlist
      storage:
        s3:
          access_key_id: ${AWS_ACCESS_KEY_ID}
          bucketnames: hfym-loki-ruler
          endpoint: ${BUCKET_ENDPOINT}
          insecure: false
          s3forcepathstyle: false
          secret_access_key: ${AWS_SECRET_ACCESS_KEY}
        type: s3
    runtime_config:
      file: /etc/loki/runtime-config/runtime-config.yaml
    schema_config:
      configs:
      - from: "2024-04-01"
        index:
          period: 24h
          prefix: loki_index_
        object_store: s3
        schema: v13
        store: tsdb
    server:
      grpc_listen_port: 9095
      http_listen_port: 3100
      http_server_read_timeout: 600s
      http_server_write_timeout: 600s
    storage_config:
      boltdb_shipper:
        index_gateway_client:
          server_address: dns+loki-backend-headless.loki.svc.cluster.local:9095
      hedging:
        at: 250ms
        max_per_second: 20
        up_to: 3
      tsdb_shipper:
        index_gateway_client:
          server_address: dns+loki-backend-headless.loki.svc.cluster.local:9095
    tracing:
      enabled: true
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: loki
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: loki
    app.kubernetes.io/version: 3.0.0
    helm.sh/chart: loki-6.6.3
  name: loki
  namespace: loki
