apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/component: memcached-results-cache
    app.kubernetes.io/instance: loki
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: loki
    app.kubernetes.io/version: 3.0.0
    helm.sh/chart: loki-6.6.3
  name: loki-results-cache
  namespace: loki
spec:
  clusterIP: None
  ports:
  - name: memcached-client
    port: 11211
    targetPort: 11211
  - name: http-metrics
    port: 9150
    targetPort: 9150
  selector:
    app.kubernetes.io/component: memcached-results-cache
    app.kubernetes.io/instance: loki
    app.kubernetes.io/name: loki
  type: ClusterIP
