apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: controller-manager
    app.kubernetes.io/instance: vault-secrets-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vault-secrets-operator
    app.kubernetes.io/version: 0.7.1
    control-plane: controller-manager
    helm.sh/chart: vault-secrets-operator-0.7.1
  name: vault-secrets-operator-metrics-service
  namespace: vault-secrets-operator
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/instance: vault-secrets-operator
    app.kubernetes.io/name: vault-secrets-operator
    control-plane: controller-manager
  type: ClusterIP
