apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: vault-secrets-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vault-secrets-operator
    app.kubernetes.io/version: 0.7.1
    helm.sh/chart: vault-secrets-operator-0.7.1
  name: vault-secrets-operator-controller-manager
  namespace: vault-secrets-operator
