apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/instance: vault-secrets-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vault-secrets-operator
    app.kubernetes.io/version: 0.7.1
    helm.sh/chart: vault-secrets-operator-0.7.1
    vso.hashicorp.com/aggregate-to-viewer: 'true'
    vso.hashicorp.com/role-instance: secrettransformation-viewer-role
  name: vault-secrets-operator-secrettransformation-viewer-role
  namespace: vault-secrets-operator
rules:
- apiGroups:
  - secrets.hashicorp.com
  resources:
  - secrettransformations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - secrets.hashicorp.com
  resources:
  - secrettransformations/status
  verbs:
  - get
