apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
  labels:
    app.kubernetes.io/instance: vault-secrets-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vault-secrets-operator
    app.kubernetes.io/version: 0.7.1
    helm.sh/chart: vault-secrets-operator-0.7.1
  name: pdcc-vault-secrets-operator
  namespace: vault-secrets-operator
spec:
  template:
    metadata:
      name: pdcc-vault-secrets-operator
    spec:
      containers:
      - args:
        - --uninstall
        - --pre-delete-hook-timeout-seconds=120
        command:
        - /vault-secrets-operator
        image: hashicorp/vault-secrets-operator:0.7.1
        name: pre-delete-controller-cleanup
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
      restartPolicy: Never
      securityContext:
        runAsNonRoot: true
      serviceAccountName: vault-secrets-operator-controller-manager
