apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/instance: vault-secrets-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vault-secrets-operator
    app.kubernetes.io/version: 0.7.1
    helm.sh/chart: vault-secrets-operator-0.7.1
    vso.hashicorp.com/aggregate-to-editor: 'true'
    vso.hashicorp.com/role-instance: hcpauth-editor-role
  name: vault-secrets-operator-hcpauth-editor-role
  namespace: vault-secrets-operator
rules:
- apiGroups:
  - secrets.hashicorp.com
  resources:
  - hcpauths
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secrets.hashicorp.com
  resources:
  - hcpauths/status
  verbs:
  - get
