apiVersion: v1
data:
  controller_manager_config.yaml: |
    apiVersion: controller-runtime.sigs.k8s.io/v1beta1
    health:
      healthProbeBindAddress: ":8081"
    kind: ControllerManagerConfig
    leaderElection:
      leaderElect: true
      resourceName: "b0d477c0.hashicorp.com"
    metrics:
      bindAddress: "127.0.0.1:8080"
    webhook:
      port: 9443
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: controller-manager
    app.kubernetes.io/instance: vault-secrets-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vault-secrets-operator
    app.kubernetes.io/version: 0.7.1
    helm.sh/chart: vault-secrets-operator-0.7.1
  name: vault-secrets-operator-manager-config
  namespace: vault-secrets-operator
