apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rook-ceph-purge-osd
  namespace: rook-ceph
rules:
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - delete
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - delete
- apiGroups:
  - ''
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - update
  - delete
  - list
