apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/created-by: helm
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: rook-ceph-operator
    helm.sh/chart: rook-ceph-v1.14.4
    operator: rook
    storage-backend: ceph
  name: rook-ceph-object-bucket
  namespace: rook-ceph
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  - configmaps
  verbs:
  - get
  - create
  - update
  - delete
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
- apiGroups:
  - objectbucket.io
  resources:
  - objectbucketclaims
  verbs:
  - list
  - watch
  - get
  - update
- apiGroups:
  - objectbucket.io
  resources:
  - objectbuckets
  verbs:
  - list
  - watch
  - get
  - create
  - update
  - delete
- apiGroups:
  - objectbucket.io
  resources:
  - objectbucketclaims/status
  - objectbuckets/status
  verbs:
  - update
- apiGroups:
  - objectbucket.io
  resources:
  - objectbucketclaims/finalizers
  - objectbuckets/finalizers
  verbs:
  - update
