apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rook-ceph-monitoring-mgr
  namespace: rook-ceph
rules:
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - list
  - create
  - update
