apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/created-by: helm
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: rook-ceph-operator
    helm.sh/chart: rook-ceph-v1.14.4
    operator: rook
    storage-backend: ceph
  name: rook-ceph-mgr
  namespace: rook-ceph
