apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: driver-ceph
    app.kubernetes.io/name: cosi-driver-ceph
    app.kubernetes.io/part-of: container-object-storage-interface
  name: objectstorage-provisioner-role-binding
  namespace: rook-ceph
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: objectstorage-provisioner-role
subjects:
- kind: ServiceAccount
  name: objectstorage-provisioner
  namespace: rook-ceph
