apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/created-by: helm
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: rook-ceph-operator
    helm.sh/chart: rook-ceph-v1.14.4
    operator: rook
    storage-backend: ceph
  name: rbd-csi-nodeplugin
  namespace: rook-ceph
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - get
  - list
- apiGroups:
  - ''
  resources:
  - persistentvolumes
  verbs:
  - get
  - list
- apiGroups:
  - storage.k8s.io
  resources:
  - volumeattachments
  verbs:
  - get
  - list
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - get
- apiGroups:
  - ''
  resources:
  - serviceaccounts
  verbs:
  - get
- apiGroups:
  - ''
  resources:
  - serviceaccounts/token
  verbs:
  - create
- apiGroups:
  - ''
  resources:
  - nodes
  verbs:
  - get
