apiVersion: v1
kind: Service
metadata:
  labels:
    tailscale.com/proxy-class: prod
  name: mongodb-1-external
  namespace: guiduck
spec:
  loadBalancerClass: tailscale
  ports:
  - port: 27017
  selector:
    app: mongodb-svc
    statefulset.kubernetes.io/pod-name: mongodb-1
  type: LoadBalancer
