apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: witherr
  namespace: poketwo-staging-private
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: witherr
  namespace: poketwo
