apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb
  namespace: poketwo-staging
spec:
  additionalMongodConfig:
    net.ipv6: true
  members: 3
  security: {}
  statefulSet:
    spec:
      template:
        spec:
          containers:
          - name: mongod
            resources:
              limits:
                cpu: 1
                memory: 20Gi
              requests:
                cpu: 100m
                memory: 1Gi
      volumeClaimTemplates:
      - metadata:
          name: data-volume
        spec:
          resources:
            requests:
              storage: 8Gi
          storageClassName: rbd-nvme-retain
  type: ReplicaSet
  users:
  - name: poketwo
    passwordSecretRef:
      name: mongodb-user
    roles:
    - db: admin
      name: root
    scramCredentialsSecretName: poketwo
  version: 7.0.11
