apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: mongodb-user
  namespace: poketwo-staging
spec:
  destination:
    create: true
    name: mongodb-user
    type: Opaque
  mount: hfym-ds
  path: poketwo-staging/mongodb-user
  type: kv-v2
