apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/component: results-cache
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mimir
    app.kubernetes.io/version: 2.12.0
    helm.sh/chart: mimir-distributed-5.3.0
  name: mimir-results-cache
  namespace: mimir
spec:
  clusterIP: None
  ports:
  - name: memcached-client
    port: 11211
    targetPort: 11211
  - name: http-metrics
    port: 9150
    targetPort: 9150
  selector:
    app.kubernetes.io/component: results-cache
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/name: mimir
  type: ClusterIP
