apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: rollout-operator
    app.kubernetes.io/version: v0.13.0
    helm.sh/chart: rollout-operator-0.14.0
  name: mimir-rollout-operator
  namespace: mimir
