apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: backblaze-b2-credentials
  namespace: mimir
spec:
  destination:
    create: true
    name: backblaze-b2-credentials
  mount: hfym-ds
  path: mimir/backblaze-b2-credentials
  type: kv-v2
