apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: test
  labels:
    app.kubernetes.io/component: smoke-test
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mimir
    app.kubernetes.io/version: 2.12.0
    helm.sh/chart: mimir-distributed-5.3.0
  name: mimir-smoke-test
  namespace: mimir
spec:
  backoffLimit: 5
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: smoke-test
        app.kubernetes.io/instance: mimir
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: mimir
        app.kubernetes.io/version: 2.12.0
        helm.sh/chart: mimir-distributed-5.3.0
    spec:
      containers:
      - args:
        - -tests.smoke-test
        - -tests.write-endpoint=http://mimir-gateway.mimir.svc:80
        - -tests.read-endpoint=http://mimir-gateway.mimir.svc:80/prometheus
        - -tests.tenant-id=
        - -tests.write-read-series-test.num-series=1000
        - -tests.write-read-series-test.max-query-age=48h
        - -server.metrics-port=8080
        envFrom:
        - secretRef:
            name: backblaze-b2-credentials
        image: grafana/mimir-continuous-test:2.12.0
        imagePullPolicy: IfNotPresent
        name: smoke-test
      initContainers: []
      restartPolicy: OnFailure
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: mimir
