apiVersion: v1
data:
  JAVA_OPTS_APPEND: -Djgroups.dns.query=keycloak-headless.keycloak.svc.cluster.local
  KEYCLOAK_ADMIN: user
  KEYCLOAK_CACHE_STACK: kubernetes
  KEYCLOAK_CACHE_TYPE: ispn
  KEYCLOAK_DATABASE_HOST: keycloak-postgres-rw
  KEYCLOAK_DATABASE_NAME: keycloak
  KEYCLOAK_DATABASE_PORT: '5432'
  KEYCLOAK_DATABASE_USER: keycloak
  KEYCLOAK_ENABLE_HTTPS: 'false'
  KEYCLOAK_ENABLE_STATISTICS: 'true'
  KEYCLOAK_HTTP_PORT: '8080'
  KEYCLOAK_LOG_LEVEL: INFO
  KEYCLOAK_LOG_OUTPUT: default
  KEYCLOAK_PRODUCTION: 'true'
  KEYCLOAK_PROXY: edge
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: keycloak
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/version: 24.0.5
    helm.sh/chart: keycloak-21.6.1
  name: keycloak-env-vars
  namespace: keycloak
