apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: gateway-proxy
  namespace: poketwo
spec:
  destination:
    create: true
    name: gateway-proxy
    type: Opaque
  mount: hfym-ds
  path: poketwo/gateway-proxy
  type: kv-v2
