apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: mongodb
  namespace: poketwo
spec:
  destination:
    create: true
    name: mongodb
    type: Opaque
  mount: hfym-ds
  path: poketwo/mongodb
  type: kv-v2
