apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    velero.io/exclude-from-backup: 'true'
  name: datadir-mongodb-1
  namespace: poketwo
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Ti
  local:
    path: /mongo
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - jolteon
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  volumeMode: Filesystem
