apiVersion: v1
kind: Service
metadata:
  annotations:
    service.kubernetes.io/topology-mode: auto
  name: imgen-rust
  namespace: poketwo
spec:
  ports:
  - port: 8000
  selector:
    app: imgen-rust
