apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-mongodb-0
  namespace: poketwo
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Ti
  local:
    path: /mongo
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - vaporeon
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  volumeMode: Filesystem
