apiVersion: v1
kind: Service
metadata:
  annotations:
    service.kubernetes.io/topology-mode: Auto
  name: image-server
  namespace: poketwo
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: image-server
