apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-proxy
  namespace: poketwo
spec:
  selector:
    matchLabels:
      app: gateway-proxy
  template:
    metadata:
      labels:
        app: gateway-proxy
    spec:
      containers:
      - image: ghcr.io/poketwo/gateway-proxy:latest
        name: server
        ports:
        - containerPort: 7878
        readinessProbe:
          httpGet:
            path: /metrics
            port: 7878
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            memory: 120Gi
          requests:
            cpu: 500m
            memory: 120Gi
        volumeMounts:
        - mountPath: /config.json
          name: config
          subPath: config.json
      imagePullSecrets:
      - name: ghcr-auth
      volumes:
      - name: config
        secret:
          secretName: gateway-proxy
