apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: poketwo
  namespace: poketwo
spec:
  destination:
    create: true
    name: poketwo
    type: Opaque
  mount: hfym-ds
  path: poketwo/poketwo
  type: kv-v2
