apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: cloudnative-pg
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cloudnative-pg
    app.kubernetes.io/version: 1.23.2
    helm.sh/chart: cloudnative-pg-0.21.5
  name: cloudnative-pg
  namespace: cloudnative-pg
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cloudnative-pg
subjects:
- kind: ServiceAccount
  name: cloudnative-pg
  namespace: cloudnative-pg
