apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  destination:
    create: true
    name: grafana-admin
    type: Opaque
  mount: hfym-ds
  path: grafana/grafana-admin
  type: kv-v2
