apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: poketwo
  namespace: argocd
spec:
  generators:
  - git:
      directories:
      - path: '*'
      repoURL: https://github.com/poketwo/nix.git
      revision: cluster
  template:
    metadata:
      name: '{{path.basename}}'
      namespace: argocd
    spec:
      destination:
        namespace: '{{path.basename}}'
        server: https://kubernetes.default.svc
      project: default
      source:
        path: '{{path}}'
        repoURL: https://github.com/poketwo/nix.git
        targetRevision: cluster
      syncPolicy:
        automated: {}
