apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: redis-ha
    chart: redis-ha-4.26.1
    heritage: Helm
    release: argocd
  name: argocd-redis-ha
  namespace: argocd
rules:
- apiGroups:
  - ''
  resources:
  - endpoints
  verbs:
  - get
