apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: application-controller
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-metrics
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: v2.11.3
    helm.sh/chart: argo-cd-7.1.3
  name: argocd-application-controller-metrics
  namespace: argocd
spec:
  ports:
  - name: http-metrics
    port: 8082
    protocol: TCP
    targetPort: metrics
  selector:
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-application-controller
  type: ClusterIP
