apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  annotations:
    helm.sh/resource-policy: no-upgrade-existing
  labels:
    app.kubernetes.io/instance: retool
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: retool
    helm.sh/chart: retool-6.0.2
  name: retool
  namespace: retool
spec:
  destination:
    create: true
    name: retool
    type: Opaque
  mount: hfym-ds
  path: retool/retool
  type: kv-v2
