apiVersion: v1
data:
  excludel2.yaml: 'announcedInterfacesToExclude:

    - ^docker.*

    - ^cbr.*

    - ^dummy.*

    - ^virbr.*

    - ^lxcbr.*

    - ^veth.*

    - ^lo$

    - ^cali.*

    - ^tunl.*

    - ^flannel.*

    - ^kube-ipvs.*

    - ^cni.*

    - ^nodelocaldns.*

    '
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: metallb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: metallb
    app.kubernetes.io/version: v0.14.5
    helm.sh/chart: metallb-0.14.5
  name: metallb-excludel2
  namespace: metallb
