apiVersion: velero.io/v1
kind: Schedule
metadata:
  labels:
    app.kubernetes.io/instance: velero
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: velero
    helm.sh/chart: velero-6.7.0
  name: velero-hourly
  namespace: velero
spec:
  schedule: 0 * * * *
  template:
    excludedNamespaces:
    - velero
    snapshotMoveData: true
    ttl: 24h
