apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade,pre-rollback
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: '5'
  labels:
    app.kubernetes.io/instance: velero
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: velero
    helm.sh/chart: velero-6.7.0
  name: velero-upgrade-crds
  namespace: velero
spec:
  backoffLimit: 3
  template:
    metadata:
      name: velero-upgrade-crds
    spec:
      containers:
      - args:
        - -c
        - /velero install --crds-only --dry-run -o yaml | /tmp/kubectl apply -f -
        command:
        - /tmp/sh
        image: velero/velero:v1.13.2
        imagePullPolicy: IfNotPresent
        name: velero
        volumeMounts:
        - mountPath: /tmp
          name: crds
      initContainers:
      - args:
        - -c
        - cp `which sh` /tmp && cp `which kubectl` /tmp
        command:
        - /bin/sh
        image: docker.io/bitnami/kubectl:1.30
        imagePullPolicy: IfNotPresent
        name: kubectl
        volumeMounts:
        - mountPath: /tmp
          name: crds
      restartPolicy: OnFailure
      serviceAccountName: velero-server-upgrade-crds
      volumes:
      - emptyDir: {}
        name: crds
