apiVersion: velero.io/v1
kind: VolumeSnapshotLocation
metadata:
  labels:
    app.kubernetes.io/instance: velero
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: velero
    helm.sh/chart: velero-6.7.0
  name: default
  namespace: velero
spec:
  provider: csi
