apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  labels:
    app.kubernetes.io/instance: rabbitmq-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: rabbitmq-cluster-operator
    app.kubernetes.io/version: 1.14.2
    helm.sh/chart: rabbitmq-cluster-operator-4.3.18
  name: rabbitmq-operator-rabbitmq-messaging-topology-operator-webhook
  namespace: rabbitmq-operator
spec:
  destination:
    create: true
    name: rabbitmq-operator-rabbitmq-messaging-topology-operator-webhook
    type: kubernetes.io/tls
  mount: hfym-ds
  path: rabbitmq-operator/rabbitmq-operator-rabbitmq-messaging-topology-operator-webhook
  type: kv-v2
