apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: rabbitmq-operator
    app.kubernetes.io/instance: rabbitmq-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: rabbitmq-cluster-operator
    app.kubernetes.io/part-of: rabbitmq
    app.kubernetes.io/version: 2.9.0
    helm.sh/chart: rabbitmq-cluster-operator-4.3.18
    rbac.authorization.k8s.io/aggregate-to-admin: 'true'
  name: rabbitmq-operator-rabbitmq-cluster-operator-rabbitmq-operator-admin
  namespace: rabbitmq-operator
rules:
- apiGroups:
  - rabbitmq.com
  resources:
  - rabbitmqclusters
  - rabbitmqclusters/finalizers
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
