apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cloudflare-api-token
  namespace: external-dns
spec:
  destination:
    create: true
    name: cloudflare-api-token
    type: Opaque
  mount: hfym-ds
  path: external-dns/cloudflare-api-token
  type: kv-v2
