apiVersion: v1
kind: Service
metadata:
  labels:
    app: trust-manager
    app.kubernetes.io/instance: trust-manager
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: trust-manager
    app.kubernetes.io/version: v0.11.0
    helm.sh/chart: trust-manager-v0.11.0
  name: trust-manager-metrics
  namespace: cert-manager
spec:
  ports:
  - name: metrics
    port: 9402
    protocol: TCP
    targetPort: 9402
  selector:
    app: trust-manager
  type: ClusterIP
