apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: trust-manager
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: trust-manager
    app.kubernetes.io/version: v0.11.0
    helm.sh/chart: trust-manager-v0.11.0
  name: trust-manager
  namespace: cert-manager
rules:
- apiGroups:
  - trust.cert-manager.io
  resources:
  - bundles
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - trust.cert-manager.io
  resources:
  - bundles/finalizers
  verbs:
  - update
- apiGroups:
  - trust.cert-manager.io
  resources:
  - bundles/status
  verbs:
  - patch
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - get
  - list
  - create
  - patch
  - watch
  - delete
- apiGroups:
  - ''
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - get
  - list
  - create
  - patch
  - watch
  - delete
