apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/instance: trust-manager
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: trust-manager
    app.kubernetes.io/version: v0.11.0
    helm.sh/chart: trust-manager-v0.11.0
  name: trust-manager
  namespace: cert-manager
spec:
  commonName: trust-manager.cert-manager.svc
  dnsNames:
  - trust-manager.cert-manager.svc
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: trust-manager
  revisionHistoryLimit: 1
  secretName: trust-manager-tls
