apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  destination:
    create: true
    name: cloudflare-api-token
  mount: hfym-ds
  path: cert-manager/cloudflare-api-token
  type: kv-v2
