apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: cluster-ca
  namespace: cert-manager
spec:
  sources:
  - secret:
      key: ca.crt
      name: cluster-ca-secret
  target:
    secret:
      key: ca.crt
