apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: trust-manager
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: trust-manager
    app.kubernetes.io/version: v0.11.0
    helm.sh/chart: trust-manager-v0.11.0
  name: trust-manager
  namespace: cert-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trust-manager
  template:
    metadata:
      labels:
        app: trust-manager
        app.kubernetes.io/instance: trust-manager
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: trust-manager
        app.kubernetes.io/version: v0.11.0
        helm.sh/chart: trust-manager-v0.11.0
    spec:
      containers:
      - args:
        - --log-format=text
        - --log-level=1
        - --metrics-port=9402
        - --readiness-probe-port=6060
        - --readiness-probe-path=/readyz
        - --trust-namespace=cert-manager
        - --webhook-host=0.0.0.0
        - --webhook-port=6443
        - --webhook-certificate-dir=/tls
        - --default-package-location=/packages/cert-manager-package-debian.json
        - --secret-targets-enabled=true
        image: quay.io/jetstack/trust-manager:v0.11.0
        imagePullPolicy: IfNotPresent
        name: trust-manager
        ports:
        - containerPort: 6443
        - containerPort: 9402
        readinessProbe:
          httpGet:
            path: /readyz
            port: 6060
          initialDelaySeconds: 3
          periodSeconds: 7
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - mountPath: /tls
          name: tls
          readOnly: true
        - mountPath: /packages
          name: packages
          readOnly: true
      initContainers:
      - args:
        - /copyandmaybepause
        - /debian-package
        - /packages
        image: quay.io/jetstack/cert-manager-package-debian:20210119.0
        imagePullPolicy: IfNotPresent
        name: cert-manager-package-debian
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - mountPath: /packages
          name: packages
          readOnly: false
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: trust-manager
      volumes:
      - emptyDir:
          sizeLimit: 50M
        name: packages
      - name: tls
        secret:
          defaultMode: 420
          secretName: trust-manager-tls
